version: "3.4"

volumes:
  db: {}

services:
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db:/var/lib/mysql
    ports: [ "127.0.0.1:33306:3306" ]
  postgres:
    image: postgres:13.4
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - db:/var/lib/postgres
    ports: [ "127.0.0.1:55432:5432" ]

